<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pilihTransaction</name>
   <tag></tag>
   <elementGuidId>a8137bfb-c91b-4e39-a89e-e0fff2884a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btn-pilih-trans-id&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-log-in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d5fef20-790b-45df-bdcc-94e83cfe2e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d6e2009c-ead6-4266-b77c-9a8147d96c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-log-in</value>
      <webElementGuid>1f0ed10c-1df4-48ed-8f36-5c4fce45ad6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>486abebb-2352-46fd-891f-105907efe619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-log-in&quot;)</value>
      <webElementGuid>65c2137b-f8b6-419b-8319-43d5ca7dfae3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
