<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_originatingAmount</name>
   <tag></tag>
   <elementGuidId>939a52af-5728-4de4-9595-e5b0d09b7d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tbl-pct-detail&quot;]/tbody/tr/td[4]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saldo-param-saldo-pc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c6511aa-e945-4320-9188-6689d5f93a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>baa51a3a-04b1-40fe-8497-377229d0faae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inp-number</value>
      <webElementGuid>0f5bcc8b-0b4d-4200-ba31-cbf520f63b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saldo-param-saldo-pc</value>
      <webElementGuid>506fb14b-b02e-46a4-8f92-05103def92bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>saldo-param-saldo-pc</value>
      <webElementGuid>bdd00d25-5ed8-4052-815d-999cea2109cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a62f2db5-2aac-4c47-b556-2a462d917cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saldo-param-saldo-pc&quot;)</value>
      <webElementGuid>8000c10e-2d28-484c-81a4-473c9779f544</webElementGuid>
   </webElementProperties>
</WebElementEntity>
