<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_transactionID</name>
   <tag></tag>
   <elementGuidId>b957d6f2-ce32-4c85-868a-f2cb405f79e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modal-tbl-trans-id&quot;]/tbody</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-check-fund0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43d07e70-dbf6-4691-a9be-6323033236e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-fund</value>
      <webElementGuid>c2f3faa3-59f0-44d7-b0f4-8c42a5b13026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PCR/24/0400/000002</value>
      <webElementGuid>8351bb2e-f438-45b5-a3ef-813998f6de3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fund[]</value>
      <webElementGuid>f92e57e9-d2cb-48ef-aeee-95d8618d53c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectedItemCek(0)</value>
      <webElementGuid>58a5c1b2-cdfd-469c-91a7-a620d7ba7bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-check-fund0</value>
      <webElementGuid>50bc38b9-2d6c-49da-a8e3-262cd723d2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e6df5c9a-4224-4f4c-940f-a85a0203904c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-check-fund0&quot;)</value>
      <webElementGuid>f361e878-8f35-41db-9451-e3fbf605c7c9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
