<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_costCenter</name>
   <tag></tag>
   <elementGuidId>837f4c73-dbcc-49c4-838f-0f552ceb3b1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modal-tbl-cost-center&quot;]/tbody/tr[4]/td[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-check-fund0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>322b798d-ed3d-448b-915c-73f7d57287d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-fund</value>
      <webElementGuid>58351c60-950f-4163-ada2-d6e3796a9c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PCR/24/0400/000002</value>
      <webElementGuid>3ed86f91-8810-434d-8cf5-61729d931b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fund[]</value>
      <webElementGuid>3bb2a0a1-adf8-44d8-9c3b-92b8ef7190e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectedItemCek(0)</value>
      <webElementGuid>8c2ae72c-d6c5-45ff-b1b0-8e50fc671e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-check-fund0</value>
      <webElementGuid>74df7aa7-12f7-440e-a775-6202eaf7f1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>441aba7b-e042-4420-aea4-3ad85d65d79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-check-fund0&quot;)</value>
      <webElementGuid>90ef1df8-e9aa-4868-92c7-2bfc68d7593b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
