<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_transaction</name>
   <tag></tag>
   <elementGuidId>2e1ccfd9-4e82-403b-844d-d8c3dc030087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Transaction-tab&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#result-tab-petty-cash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b74ca99-4e30-4ec5-8df4-e52a8440c5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-result-saldo-petty-cash</value>
      <webElementGuid>54c56121-dd3d-4625-976b-d13100225af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>result-tab-petty-cash</value>
      <webElementGuid>a89a7a50-0aa5-4c2e-9e04-3b965d6c3748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tab-result-saldo-petty-cash</value>
      <webElementGuid>826e11e2-085b-4adb-b484-61da7fc2163c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c97dcdfd-b653-4592-9e43-6ac1e072b5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>99ec9c53-4321-4e04-b557-66b6765bd4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Result</value>
      <webElementGuid>67bde259-136b-40b0-a9cd-683cd8d19afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result-tab-petty-cash&quot;)</value>
      <webElementGuid>79935944-5f94-4b16-90e7-88868cf88798</webElementGuid>
   </webElementProperties>
</WebElementEntity>
